export const GET_ALL_CLASSES = 'classes/GET_ALL_CLASSES';

export const ADD_CLASS_TO_USER = 'classes/ADD_CLASS_TO_USER';
export const ADD_CLASS_TO_USER_SUCCESS = 'classes/ADD_CLASS_TO_USER_SUCCESS';
export const ADD_CLASS_TO_USER_FAIL = 'classes/ADD_CLASS_TO_USER_FAIL';

export const REMOVE_CLASS_FROM_USER = 'classes/REMOVE_CLASS_FROM_USER'; 
export const REMOVE_CLASS_FROM_USER_SUCCESS = 'classes/REMOVE_CLASS_FROM_USER_SUCCESS';
export const REMOVE_CLASS_FROM_USER_FAIL = 'classes/REMOVE_CLASS_FROM_USER_FAIL';

export const REFRESH_CLASSES = 'classes/REFRESH_CLASSES'; 
