---
sudo: required
dist: trusty
language: node_js
node_js:
  # LTS version
  - "10.0.0"
notifications:
  email:
    on_success: change # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - dev+dianoia.travis.build@church.technology
cache:
  directories:
    - node_modules
before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
install:
  - npm install
  # - npm i -g react-deploy-cli
before_script:
  - export RELEASE_HEAD=$(git rev-parse --short HEAD | cut -c1-7)  
  - export RELEASE_HEAD_LONG=$(git rev-parse HEAD)  
  - export CI=false
script:
  - npm run-script build 
# deploy:
#   skip_cleanup: true
#   provider: script
#   script: react-deploy deploy $TRAVIS_BRANCH && react-deploy list $TRAVIS_BRANCH && react-deploy activate $RELEASE_HEAD $TRAVIS_BRANCH
#   on:
#     branch: ["master"]