export const UPDATE_JWT = 'user/UPDATE_JWT'; 

export const SUBMIT_LOGIN = 'user/SUBMIT_LOGIN'
export const LOGIN_SUBMIT_SUCCESS = 'user/LOGIN_SUBMIT_SUCCESS'; 
export const LOGIN_SUBMIT_FAIL = 'user/LOGIN_SUBMIT_FAIL'; 

export const LOGOUT = 'user/LOGOUT'; 
export const RESET_USER= "user/RESET_USER"; 

export const REFRESH_USER = 'user/REFRESH_USER';
export const REFRESH_USER_CLASSES = 'user/REFRESH_USER_CLASSES'; 
export const REFRESH_USER_DECKS = 'user/REFRESH_USER_DECKS'; 
// TODO: add other refresh options

export const SUBMIT_REGISTRATION = 'user/SUBMIT_REGISTRATION';
export const REGISTRATION_SUBMIT_SUCCESS = 'user/REGISTRATION_SUBMIT_SUCCESS'; 
export const REGISTRATION_SUBMIT_FAIL = 'user/REGISTRATION_SUBMIT_FAIL'; 

export const SUBMIT_FORGOT_PASSWORD = 'user/SUBMIT_FORGOT_PASSWORD'; 
export const SUBMIT_FORGOT_PASSWORD_SUCCESS = 'user/SUBMIT_FORGOT_PASSWORD_SUCCESS'; 
export const SUBMIT_FORGOT_PASSWORD_FAIL = 'user/SUBMIT_FORGOT_PASSWORD_FAIL'; 

export const SUBMIT_RESET_PASSWORD = 'user/SUBMIT_RESET_PASSWORD';
export const SUBMIT_RESET_PASSWORD_SUCCESS = 'user/SUBMIT_RESET_PASSWORD_SUCCESS';
export const SUBMIT_RESET_PASSWORD_FAIL = 'user/SUBMIT_RESET_PASSWORD_FAIL'; 