export const SUBMIT_REGISTRATION = 'registrationPage/SUBMIT_REGISTRATION';
export const REGISTRATION_SUBMIT_SUCCESS = 'registrationPage/REGISTRATION_SUBMIT_SUCCESS'; 
export const REGISTRATION_SUBMIT_FAIL = 'registrationPage/REGISTRATION_SUBMIT_FAIL'; 