export const GET_ALL_USER_DECKS = 'decks/GET_ALL_USER_DECKS'; 
export const REFRESH_ALL_USER_DECKS = 'decks/REFRESH_ALL_USER_DECKS'; 

export const ADD_DECK_TO_USER = 'decks/ADD_DECK_TO_USER'; 
export const ADD_DECK_TO_USER_SUCCESS = 'decks/ADD_DECK_TO_USER_SUCCESS'; 

export const REMOVE_DECK_FROM_USER = 'decks/REMOVE_DECK_FROM_USER'; 
export const REMOVE_DECK_FROM_USER_SUCCESS = 'decks/REMOVE_DECK_FROM_USER_SUCCESS'; 
